#!/usr/bin/env python
import sys
sys.path.append('Core')
import repl
import interp
import read
run_conflict = ""

def main():
    if sys.argv[1] == "-r":
        repl.repl(">>> ")
    if sys.argv[1] == "-l":
        read.openfile(sys.argv[2])
    if sys.argv[1] == "-s":
        read.openfile(sys.argv[2])
        repl.repl(">>> ")
if __name__ == "__main__":
    main()
    

